#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

cd /var/www/html

php maintenance/install.php \
  --server=http://localhost:4000 \
  --dbtype sqlite \
  --dbpath cache/ \
  --scriptpath '' \
  --pass adminpassword \
  MediaWiki \
  Admin

echo "require_once 'NoWikiSettings.php';" >> LocalSettings.php

for file in /workspace/src/*; do
  title="$(basename "$file" | sed -e 's/.wikitext//')"
  php maintenance/edit.php \
    --no-rc \
    "$title" < "$file"
done

php maintenance/rebuildFileCache.php --start 1 --all
