#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

cd /var/www/html

php maintenance/install.php \
  --server=http://localhost:4000 \
  --dbtype sqlite \
  --dbpath cache/ \
  --scriptpath '' \
  --pass adminpassword \
  MediaWiki \
  Admin

echo "require_once 'NoWikiSettings.php';" >> LocalSettings.php

echo 'Index' | php maintenance/edit.php 'MediaWiki:Mainpage'
php extensions/ThisIsNotAWiki/maintenance/importWikitext.php /workspace/src/

php maintenance/purgeList.php --namespace=0
php maintenance/rebuildFileCache.php --overwrite

php extensions/ThisIsNotAWiki/maintenance/replaceNamespace.php /workspace/dist/
rm -rf /workspace/dist/history/
