#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

cd /var/www/html

php maintenance/install.php \
  --server=http://localhost:4000 \
  --dbtype sqlite \
  --dbpath cache/ \
  --scriptpath '' \
  --pass adminpassword \
  MediaWiki \
  Admin

echo "require_once 'NoWikiSettings.php';" >> LocalSettings.php

# TODO create xmls
# TODO import xmls

php maintenance/rebuildFileCache.php;
